"""
Astro Schema Renderer for Resume Sync

Generates TypeScript schema file (resume-schema.ts) for the Astro site.
This creates a single source of truth that Astro components import for:
  - Type-safe field rendering
  - Section layout configuration (sidebar vs main)
  - Theme variables (colors, fonts, spacing)

Output File: src/data/resume-schema.ts

Schema Structure:
  - sectionSchemas[]: Array of section configs with type, title, sidebar, fields
  - theme: Colors, fonts, spacing, borders from 00-config.md

No hardcoded defaults - all values come from the markdown config files.
"""


def snake_to_camel(s):
    """
    Convert snake_case to camelCase for JavaScript compatibility.

    Examples:
      text_secondary -> textSecondary
      size_base -> sizeBase
      container_max_width -> containerMaxWidth
    """
    parts = s.split('_')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


def generate(data, theme_config):
    """
    Generate TypeScript schema file for Astro site.

    Args:
        data: Resume data with 'sections' list
        theme_config: Theme config from 00-config.md (colors, fonts, spacing, borders)

    Returns:
        Complete TypeScript file content as string
    """
    sections = data.get('sections', [])

    # --- Build Section Schemas ---
    # Each section becomes an object with type, title, sidebar, fields, renderAsCategories
    section_schemas = []

    for section in sections:
        section_type = section.get('type', 'plaintext')
        title = section.get('title', '')
        fields = section.get('fields', {})
        render_as_categories = section.get('render_as_categories', False)
        sidebar = section.get('sidebar', False)

        # Convert fields to TypeScript format
        # Simple: "header" -> { type: "header" }
        # Complex: {"type": "inline", "prefix": "GPA "} -> { type: "inline", prefix: "GPA " }
        fields_ts = []
        for field_name, field_config in fields.items():
            if isinstance(field_config, str):
                fields_ts.append(f'    {field_name}: {{ type: "{field_config}" }}')
            elif isinstance(field_config, dict):
                field_type = field_config.get('type', 'text')
                prefix = field_config.get('prefix', '')
                prefix_str = f', prefix: "{prefix}"' if prefix else ''
                fields_ts.append(f'    {field_name}: {{ type: "{field_type}"{prefix_str} }}')

        fields_block = ',\n'.join(fields_ts) if fields_ts else ''

        # Build section object
        section_schemas.append(f'''  {{
    type: "{section_type}",
    title: {f'"{title}"' if title else 'null'},
    sidebar: {str(sidebar).lower()},
    renderAsCategories: {str(render_as_categories).lower()},
    fields: {{
{fields_block}
    }}
  }}''')

    sections_block = ',\n'.join(section_schemas)

    # --- Build Theme TypeScript ---
    # All values come from config, converted to camelCase for JS
    theme = theme_config.get('theme', {})
    colors = theme.get('colors', {})
    fonts = theme.get('fonts', {})
    spacing = theme.get('spacing', {})
    borders = theme.get('borders', {})

    # Generate theme property blocks
    # Colors: snake_case keys -> camelCase (text_secondary -> textSecondary)
    colors_ts = ',\n    '.join(f'{snake_to_camel(k)}: "{v}"' for k, v in colors.items())

    # Fonts: Handle 'family' specially (uses single quotes for font stack)
    fonts_ts = ',\n    '.join(
        f'{snake_to_camel(k)}: "{v}"' if k != 'family' else f'{k}: \'{v}\''
        for k, v in fonts.items()
    )

    # Spacing: snake_case -> camelCase
    spacing_ts = ',\n    '.join(f'{snake_to_camel(k)}: "{v}"' for k, v in spacing.items())

    # Borders: Keep as-is (header, section)
    borders_ts = ',\n    '.join(f'{k}: "{v}"' for k, v in borders.items())

    # --- Assemble TypeScript File ---
    ts_content = f'''// AUTO-GENERATED by resume/scripts/sync.py
// Do not edit manually - changes will be overwritten
// Source: resume/sections/**/*.md and resume/00-config.md

export interface FieldConfig {{
  type: string;
  prefix?: string;
}}

export interface SectionSchema {{
  type: string;
  title: string | null;
  sidebar: boolean;
  renderAsCategories: boolean;
  fields: Record<string, FieldConfig>;
}}

export const sectionSchemas: SectionSchema[] = [
{sections_block}
];

export const theme = {{
  colors: {{
    {colors_ts}
  }},
  fonts: {{
    {fonts_ts}
  }},
  spacing: {{
    {spacing_ts}
  }},
  borders: {{
    {borders_ts}
  }},
}} as const;

// Helper to get field type from config
export function getFieldType(fieldConfig: FieldConfig | string): string {{
  return typeof fieldConfig === "string" ? fieldConfig : fieldConfig.type;
}}

// Helper to get field prefix from config
export function getFieldPrefix(fieldConfig: FieldConfig | string): string {{
  if (typeof fieldConfig === "object" && fieldConfig.prefix) {{
    return fieldConfig.prefix;
  }}
  return "";
}}
'''

    return ts_content
