// AUTO-GENERATED by resume/scripts/sync.py
// Do not edit manually - changes will be overwritten
// Source: resume/sections/**/*.md and resume/00-config.md

export interface FieldConfig {
  type: string;
  prefix?: string;
}

export interface SectionSchema {
  type: string;
  title: string | null;
  sidebar: boolean;
  renderAsCategories: boolean;
  fields: Record<string, FieldConfig>;
}

export const sectionSchemas: SectionSchema[] = [
  {
    type: "personal",
    title: null,
    sidebar: false,
    renderAsCategories: false,
    fields: {
    name: { type: "header" },
    title: { type: "subheader" },
    email: { type: "inline", prefix: "Email: " },
    GitHub: { type: "inline", prefix: "GitHub: " },
    LinkedIn: { type: "inline", prefix: "LinkedIn: " }
    }
  },
  {
    type: "plaintext",
    title: "SUMMARY",
    sidebar: false,
    renderAsCategories: false,
    fields: {

    }
  },
  {
    type: "education",
    title: "EDUCATION",
    sidebar: true,
    renderAsCategories: false,
    fields: {
    degree: { type: "header" },
    institution: { type: "subheader" },
    graduation: { type: "inline" },
    gpa: { type: "inline", prefix: "GPA " }
    }
  },
  {
    type: "skills",
    title: "TECHNICAL SKILLS",
    sidebar: true,
    renderAsCategories: true,
    fields: {
    category: { type: "subheader" }
    }
  },
  {
    type: "experience",
    title: "PROFESSIONAL EXPERIENCE",
    sidebar: false,
    renderAsCategories: false,
    fields: {
    position: { type: "header" },
    company: { type: "subheader" },
    duration: { type: "inline" }
    }
  },
  {
    type: "projects",
    title: "PROJECTS",
    sidebar: false,
    renderAsCategories: false,
    fields: {
    title: { type: "header" },
    duration: { type: "subheader" }
    }
  }
];

export const theme = {
  colors: {
    h1: "#003940",
    h2: "#006969",
    h3: "#008a75",
    h4: "#339c8c",
    text: "#074747",
    textSecondary: "#6b7878",
    background: "#fff",
    highlight: "#deffff",
    border: "#e5e5e5"
  },
  fonts: {
    family: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    sizeBase: "15px",
    sizeH1: "2.5rem",
    sizeH2: "1.25rem",
    sizeH3: "1.05rem",
    sizeSmall: "0.9rem"
  },
  spacing: {
    containerMaxWidth: "800px",
    containerPadding: "3rem 2rem",
    sectionMargin: "2rem",
    itemMargin: "1.5rem"
  },
  borders: {
    header: "2px solid",
    section: "1px solid"
  },
} as const;

// Helper to get field type from config
export function getFieldType(fieldConfig: FieldConfig | string): string {
  return typeof fieldConfig === "string" ? fieldConfig : fieldConfig.type;
}

// Helper to get field prefix from config
export function getFieldPrefix(fieldConfig: FieldConfig | string): string {
  if (typeof fieldConfig === "object" && fieldConfig.prefix) {
    return fieldConfig.prefix;
  }
  return "";
}
